[package]
name = "varu64"
version = "0.6.0"
authors = ["AljoschaMeyer <mail@aljoscha-meyer.de>"]
description = "A variable length encoding for unsigned 64 bit integers."
repository = "https://github.com/AljoschaMeyer/varu64-rs"
readme = "README.md"
license = "AGPL-3.0"
